require 'settings'
require 'colorschame'
require 'keys'
require 'plugins'

require 'config.autopairs-config'
require 'config.autotag-config'
require 'config.barbar-config'
require 'config.colorizer-config'
require 'config.comments-config'
require 'config.compe-config'
require 'config.galaxyline-config'
require 'config.lsp-colors-config'
require 'config.matchup-config'
require 'config.nvim-tree-config'
require 'config.treesitter-config'
require 'config.trouble-config'
require 'config.undotree-config'
-- require 'config.zen-config'      -- TODO configure zen mode
-- require 'config.latex-live-preview-config'
-- require 'config.glow-config'

require 'lsp.lua-lsp'
require 'lsp.python-lsp'
require 'lsp.bash-lsp'
--require 'lsp.ccls-lsp'
require 'lsp.clangd-lsp'
-- require 'lsp.haskell-lsp'
-- require 'lsp.latex-lsp'
-- require 'lsp.js-ts-lsp'
