require 'settings'
require 'plugins'
require 'colorschame'

require 'config..nvim-tree-config'
require 'config.barbar-config'
require 'config.colorizer-config'
require 'config.comments-config'
require 'config.compe-config'
require 'config.galaxyline-config'
require 'config.lsp-colors-config'
require 'config.treesitter-config'
require 'config.trouble-config'
require 'config.autopair'

require 'config.zenmode'
require 'lsp.lua-lsp'
require 'lsp.python-lsp'
require 'lsp.bash-lsp'
--require 'lsp.ccls-lsp'
require 'lsp.clangd-lsp'
-- require 'lsp.haskell-lsp'
-- require 'lsp.latex-lsp'
require 'lsp.js-ts-lsp'

require 'keys'
