#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


#### BSPWM configuration ####

bspc config automatic_scheme 	            longest_side 
bspc config borderless_monocle            true
bspc config border_width 								  2
bspc config bottom_padding                0
bspc config click_to_focus                false
bspc config focus_by_distance             true
#bspc config focused_border_color          \#FEFEFE
bspc config focus_follows_pointer         true
bspc config gapless_monocle               true
bspc config history_aware_focus           true
bspc config ignore_ewmh_focus 		  			true
bspc config initial_polarity 	            first_child
bspc config left_padding                  0
bspc config merge_overlapping_monitors    true
#bspc config normal_border_color           \#111824
bspc config paddingless_monocle  	  			true
bspc config pointer_action1 	            move 
bspc config pointer_action2               resize_side
bspc config pointer_action3               resize_corner
bspc config pointer_follows_focus 	      false 
bspc config pointer_follows_monitor 			true
bspc config pointer_modifier              mod4
bspc config remove_disabled_monitors      true
bspc config right_padding 								0
bspc config single_monocle                false
bspc config split_ratio                   0.50
bspc config top_monocle_padding 					0
bspc config top_padding 									33
bspc config window_gap 			  						8

bspc monitor -d I II III IV V VI VII VIII IX X

# bspc config external_rules_command  $HOME/.config/bspwm/external_rules.sh

# bspc rule -a Alacritty   desktop='^1' follow=on  state=pseudo_tiled
# bspc rule -a qutebrowser desktop='^2' 
# bspc rule -a newsboat    desktop='^4' follow=on  state=pseudo_tiled
# bspc rule -a Vim         desktop='^5' follow=on  state=pseudo_tiled
# bspc rule -a Zathura     desktop='^6' follow=on  state=pseudo_tiled
# bspc rule -a Sxiv        desktop='^6' follow=off 
# bspc rule -a Gimp        desktop='^7'            state=floating 
# bspc rule -a mpv                                 state=floating     focus=off 
# bspc rule -a scratchpad                          state=floating     locked=on sticky=on hidden=on
# bspc rule -a lf                                  state=floating     locked=on sticky=on hidden=on
# 
# bspc desktop '^3' -l monocle


