#!/usr/bin/env bash

zscroll --before-text "♪ x" --delay 0.3 \
		--match-command "mpc status" \
		--match-text "playing" "--before-text 'ﱘ '" \
		--match-text "paused" "--before-text 'ﱙ ' --scroll 0" \
		--update-check true "mpc current" &

wait
